config/routes.rb
Rails.application.routes.draw do
  resources :employees
  get 'alerts/index', as: :alert

  resources :fake_secads

  get 'api/me'
  get 'api/me/profile' => "api#profile"
  get 'api/departments_by_ug'
  get 'api/servers_by_ug'
  post 'api/sign_by_password'
  post 'api/get_token'

  use_doorkeeper

  devise_for :users
  resources :users do
    member do
      patch "change_avatar"
    end
    collection do
      get "clear_coockie"
      post "autenticar_service"
      get "login_secad"
    end
  end

  get "minha_pagina" => "users#minha_pagina", as: :minha_pagina
  get "meus_dados" => "users#dados_api", as: :meus_dados
  get "password" => "users#password", as: :minha_senha
  get "senha_sucesso" => "users#senha_sucesso", as: :senha_sucesso
  post "password_change" => "users#password_change"

  authenticated :user do
    root "users#minha_pagina"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  scope "/admin" do
    resources :users
  end

end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id                :integer          not null, primary key
#  matricula         :string
#  numfunc           :integer
#  numvinc           :integer
#  nome              :string
#  sexo              :string
#  numrg             :string
#  orgaorg           :string
#  ufrg              :string
#  cpf               :string
#  data_admissao     :date
#  telefone          :string
#  endereco          :string
#  bairro            :string
#  cidade            :string
#  cep               :string
#  uf                :string
#  data_nascimento   :date
#  data_base_ferias  :date
#  email             :string
#  cargo             :string
#  funcao            :string
#  orgao             :string
#  cod_orgao         :integer
#  salario           :decimal(, )
#  gratificacao      :decimal(, )
#  tipo_vinculo      :string
#  data_demissao     :date
#  data_fim_contrato :date
#  escolaridade      :string
#  situacao          :string
#  referencia_cargo  :string
#  pis               :string
#  referencia_funcao :string
#  dtini_ferias      :date
#  dtfim_ferias      :date
#  sigla_orgao       :string
#  agencia           :string
#  conta             :string
#  banco             :string
#  situacao_ferias   :string
#  cnpj_orgao        :string
#  poder             :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Employee < ApplicationRecord

  default_scope -> {order(nome: :asc)}

  def self.importar
    servidores = Secad.where(cod_orgao: 13)

    servidores.each do |s|
      servidor = Employee.find_or_create_by(cpf: s.cpf)
      servidor.matricula = s.matricula
      servidor.numfunc = s.numfunc
      servidor.numvinc = s.numvinc
      servidor.nome = s.nome
      servidor.sexo = s.sexo
      servidor.numrg = s.numrg
      servidor.orgaorg = s.orgaorg
      servidor.ufrg = s.ufrg
      servidor.cpf = s.cpf
      servidor.data_admissao = s.data_admissao
      servidor.telefone = s.telefone
      servidor.endereco = s.endereco
      servidor.bairro = s.bairro
      servidor.cidade = s.cidade
      servidor.cep = s.cep
      servidor.uf = s.uf
      servidor.data_nascimento = s.data_nascimento
      servidor.data_base_ferias = s.data_base_ferias
      servidor.email = s.email
      servidor.cargo = s.cargo
      servidor.funcao = s.funcao
      servidor.orgao = s.orgao
      servidor.cod_orgao = s.cod_orgao
      servidor.salario = s.salario
      servidor.gratificacao = s.gratificacao
      servidor.tipo_vinculo = s.tipo_vinculo
      servidor.data_demissao = s.data_demissao
      servidor.data_fim_contrato = s.data_fim_contrato
      servidor.escolaridade = s.escolaridade
      servidor.situacao = s.situacao
      servidor.referencia_cargo = s.referencia_cargo_
      servidor.pis = s.pis
      servidor.referencia_funcao = s.referencia_funcao_
      servidor.dtini_ferias = s.dtini_ferias
      servidor.dtfim_ferias = s.dtfim_ferias
      servidor.sigla_orgao = s.sigla_orgao
      servidor.agencia = s.agencia
      servidor.conta = s.conta
      servidor.banco = s.banco
      servidor.situacao_ferias = s.situacao_ferias
      servidor.cnpj_orgao = s.cnpj_orgao

      servidor.save

    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    if current_user.admin
      @q = Employee.ransack(params[:q])
    else
      @q = Employee.where(cod_orgao: current_user.profile.cod_orgao).ransack(params[:q])
    end

    @employees = @q.result.page(params[:page]).per(50)
    render layout: "material"
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    render layout: "material"
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    render layout: "material"
  end

  # GET /employees/1/edit
  def edit
    render layout: "material"
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:matricula, :numfunc, :numvinc, :nome, :sexo, :numrg, :orgaorg, :ufrg, :cpf, :data_admissao, :telefone, :endereco, :bairro, :cidade, :cep, :uf, :data_nascimento, :data_base_ferias, :email, :cargo, :funcao, :orgao, :cod_orgao, :salario, :gratificacao, :tipo_vinculo, :data_demissao, :data_fim_contrato, :escolaridade, :situacao, :referencia_cargo, :pis, :referencia_funcao, :dtini_ferias, :dtfim_ferias, :sigla_orgao, :agencia, :conta, :banco, :situacao_ferias, :cnpj_orgao, :poder)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-content">
      <span class="card-title black-text"><b>Dados Pessoais</b></span>
      <div class="row">
        <div class="field col s12 l8">
          <%= form.label :nome %>
          <%= form.text_field :nome, id: :employee_nome %>
        </div>

        <div class="field col s12 l4">
          <%= form.label :sexo %>
          <%= form.text_field :sexo, id: :employee_sexo %>
        </div>
        <div class="field col s12 l3">
          <%= form.label :cpf %>
          <%= form.text_field :cpf, id: :employee_cpf %>
        </div>
        <div class="field col s12 l3">
          <%= form.label :pis %>
          <%= form.text_field :pis, id: :employee_pis %>
        </div>
        <div class="field col s12 l3">
          <%= form.label :numrg %>
          <%= form.text_field :numrg, id: :employee_numrg %>
        </div>

        <div class="field col s12 l3">
          <%= form.label :orgaorg %>
          <%= form.text_field :orgaorg, id: :employee_orgaorg %>
        </div>

        <div class="field col s12 l3">
          <%= form.label :ufrg %>
          <%= form.text_field :ufrg, id: :employee_ufrg %>
        </div>

        <div class="field col s12 l3">
          <%= form.label :telefone %>
          <%= form.text_field :telefone, id: :employee_telefone %>
        </div>
        <div class="field  col s12 l6">
          <%= form.label :endereco %>
          <%= form.text_field :endereco, id: :employee_endereco %>
        </div>

        <div class="field col s12 l3">
          <%= form.label :bairro %>
          <%= form.text_field :bairro, id: :employee_bairro %>
        </div>

        <div class="field  col s12 l6">
          <%= form.label :cidade %>
          <%= form.text_field :cidade, id: :employee_cidade %>
        </div>

        <div class="field col s12 l6">
          <%= form.label :cep %>
          <%= form.text_field :cep, id: :employee_cep %>
        </div>
        <div class="field col s12 l6">
          <%= form.label :uf %>
          <%= form.text_field :uf, id: :employee_uf %>
        </div>

        <div class="field col s12 l6">
          <%= form.label :data_nascimento %>
          <%= form.date_field :data_nascimento, id: :employee_data_nascimento %>
        </div>
        <div class="field col s12 l6">
          <%= form.label :email %>
          <%= form.text_field :email, id: :employee_email %>
        </div>

        <div class="field col s12 l4">
          <%= form.label :banco %>
          <%= form.text_field :banco, id: :employee_banco %>
        </div>
        <div class="field col s12 l4">
          <%= form.label :agencia %>
          <%= form.text_field :agencia, id: :employee_agencia %>
        </div>

        <div class="field col s12 l4">
          <%= form.label :conta %>
          <%= form.text_field :conta, id: :employee_conta %>
        </div>
        <div class="field col s12 l4">
          <%= form.label :escolaridade %>
          <%= form.text_field :escolaridade, id: :employee_escolaridade %>
        </div>


      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-content">
      <span class="card-title black-text"><b>Dados Funcionais</b></span>
      <div class="row">
        <div class="field col s12 l4">
          <%= form.label :matricula %>
          <%= form.text_field :matricula, id: :employee_matricula %>
        </div>

        <div class="field col s12 l4">
          <%= form.label :numfunc %>
          <%= form.number_field :numfunc, id: :employee_numfunc %>
        </div>

        <div class="field col s12 l4">
          <%= form.label :numvinc %>
          <%= form.number_field :numvinc, id: :employee_numvinc %>
        </div>


        <div class="field col s12 l3">
          <%= form.label :data_admissao %>
          <%= form.date_field :data_admissao, id: :employee_data_admissao %>
        </div>
        <div class="field col s12 l3">
          <%= form.label :data_base_ferias %>
          <%= form.date_field :data_base_ferias, id: :employee_data_base_ferias %>
        </div>
        <div class="field col s12 l3">
          <%= form.label :data_demissao %>
          <%= form.date_field :data_demissao, id: :employee_data_demissao %>
        </div>

        <div class="field col s12 l3">
          <%= form.label :data_fim_contrato %>
          <%= form.date_field :data_fim_contrato, id: :employee_data_fim_contrato %>
        </div>

        <div class="field col s12 l6">
          <%= form.label :dtini_ferias %>
          <%= form.date_field :dtini_ferias, id: :employee_dtini_ferias %>
        </div>

        <div class="field col s12 l6">
          <%= form.label :dtfim_ferias %>
          <%= form.date_field :dtfim_ferias, id: :employee_dtfim_ferias %>
        </div>
      </div>
      <div class="row">
        <div class="field col s12 l18">
          <%= form.label :orgao %>
          <%= form.text_field :orgao, id: :employee_orgao %>
        </div>
        <div class="field  col s12 l2">
          <%= form.label :sigla_orgao %>
          <%= form.text_field :sigla_orgao, id: :employee_sigla_orgao %>
        </div>
        <div class="field  col s12 l2">
          <%= form.label :cod_orgao %>
          <%= form.number_field :cod_orgao, id: :employee_cod_orgao %>
        </div>
        <div class="field col s12 ">
          <%= form.label :cnpj_orgao %>
          <%= form.text_field :cnpj_orgao, id: :employee_cnpj_orgao %>
        </div>
        <div class="field col s12 l6">
          <%= form.label :cargo %>
          <%= form.text_field :cargo, id: :employee_cargo %>
        </div>

        <div class="field col s12 l6">
          <%= form.label :funcao %>
          <%= form.text_field :funcao, id: :employee_funcao %>
        </div>
        <div class="field col s12 l6">
          <%= form.label :referencia_cargo %>
          <%= form.text_field :referencia_cargo, id: :employee_referencia_cargo %>
        </div>



        <div class="field col s12 l6">
          <%= form.label :referencia_funcao %>
          <%= form.text_field :referencia_funcao, id: :employee_referencia_funcao %>
        </div>

      </div>
      <div class="row">
        <div class="field col s12 l6">
          <%= form.label :salario %>
          <%= form.text_field :salario, id: :employee_salario %>
        </div>

        <div class="field col s12 l6">
          <%= form.label :gratificacao %>
          <%= form.text_field :gratificacao, id: :employee_gratificacao %>
        </div>

        <div class="field col s12 l6">
          <%= form.label :tipo_vinculo %>
          <%= form.text_field :tipo_vinculo, id: :employee_tipo_vinculo %>
        </div>




        <div class="field col s12 l6">
          <%= form.label :situacao %>
          <%= form.text_field :situacao, id: :employee_situacao %>
        </div>

        <div class="field col s12 l6">
          <%= form.label :situacao_ferias %>
          <%= form.text_field :situacao_ferias, id: :employee_situacao_ferias %>
        </div>
      </div>
    </div>
  </div>





  <div class="field">
    <%= form.label :poder %>
    <%= form.text_field :poder, id: :employee_poder %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", class:"btn", target: "_self" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1 class=" center-align">Editar Servidor</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Servidores', employees_path, target:"_self" %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servidores</h1>
<div class="card" style="overflow: visible;">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
        <%= f.text_field :nome_or_cpf_cont, placeholder: "Nome, CPF" %>
        <br><br>
        <%= f.submit "Filtrar", class:"btn white-text" %>
        <%= link_to "Limpar", employees_path, class:"btn white-text" %>
      <% end %>
    </div>
  </div>
</div>

<%= paginate @employees %>
<div class="card-panel">
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th>Órgão</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>

        <td><%= link_to employee.nome, employee, target:"_self" %></td>
        <td><%= employee.cpf %></td>
        <td><%= employee.orgao %></td>
        <td><%= link_to 'Editar', edit_employee_path(employee) %></td>
        <td><%= link_to 'Excluir', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= paginate @employees %>
<br>

<%= link_to 'Novo Servidor', new_employee_path, class:"btn white-text", target:"_self" %>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @employee.matricula %>
</p>

<p>
  <strong>Numfunc:</strong>
  <%= @employee.numfunc %>
</p>

<p>
  <strong>Numvinc:</strong>
  <%= @employee.numvinc %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @employee.nome %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @employee.sexo %>
</p>

<p>
  <strong>Numrg:</strong>
  <%= @employee.numrg %>
</p>

<p>
  <strong>Orgaorg:</strong>
  <%= @employee.orgaorg %>
</p>

<p>
  <strong>Ufrg:</strong>
  <%= @employee.ufrg %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @employee.cpf %>
</p>

<p>
  <strong>Data admissao:</strong>
  <%= @employee.data_admissao %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @employee.telefone %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @employee.endereco %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @employee.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @employee.cidade %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @employee.cep %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @employee.uf %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @employee.data_nascimento %>
</p>

<p>
  <strong>Data base ferias:</strong>
  <%= @employee.data_base_ferias %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @employee.cargo %>
</p>

<p>
  <strong>Funcao:</strong>
  <%= @employee.funcao %>
</p>

<p>
  <strong>Orgao:</strong>
  <%= @employee.orgao %>
</p>

<p>
  <strong>Cod orgao:</strong>
  <%= @employee.cod_orgao %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @employee.salario %>
</p>

<p>
  <strong>Gratificacao:</strong>
  <%= @employee.gratificacao %>
</p>

<p>
  <strong>Tipo vinculo:</strong>
  <%= @employee.tipo_vinculo %>
</p>

<p>
  <strong>Data demissao:</strong>
  <%= @employee.data_demissao %>
</p>

<p>
  <strong>Data fim contrato:</strong>
  <%= @employee.data_fim_contrato %>
</p>

<p>
  <strong>Escolaridade:</strong>
  <%= @employee.escolaridade %>
</p>

<p>
  <strong>Situacao:</strong>
  <%= @employee.situacao %>
</p>

<p>
  <strong>Referencia cargo:</strong>
  <%= @employee.referencia_cargo %>
</p>

<p>
  <strong>Pis:</strong>
  <%= @employee.pis %>
</p>

<p>
  <strong>Referencia funcao:</strong>
  <%= @employee.referencia_funcao %>
</p>

<p>
  <strong>Dtini ferias:</strong>
  <%= @employee.dtini_ferias %>
</p>

<p>
  <strong>Dtfim ferias:</strong>
  <%= @employee.dtfim_ferias %>
</p>

<p>
  <strong>Sigla orgao:</strong>
  <%= @employee.sigla_orgao %>
</p>

<p>
  <strong>Agencia:</strong>
  <%= @employee.agencia %>
</p>

<p>
  <strong>Conta:</strong>
  <%= @employee.conta %>
</p>

<p>
  <strong>Banco:</strong>
  <%= @employee.banco %>
</p>

<p>
  <strong>Situacao ferias:</strong>
  <%= @employee.situacao_ferias %>
</p>

<p>
  <strong>Cnpj orgao:</strong>
  <%= @employee.cnpj_orgao %>
</p>

<p>
  <strong>Poder:</strong>
  <%= @employee.poder %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>