config/routes.rb
Rails.application.routes.draw do
  resources :employees
  get 'alerts/index', as: :alert

  resources :fake_secads

  get 'api/me'
  get 'api/me/profile' => "api#profile"
  get 'api/departments_by_ug'
  get 'api/servers_by_ug'
  post 'api/sign_by_password'
  post 'api/get_token'

  use_doorkeeper

  devise_for :users
  resources :users do
    member do
      patch "change_avatar"
    end
    collection do
      get "clear_coockie"
      post "autenticar_service"
      get "login_secad"
    end
  end

  get "minha_pagina" => "users#minha_pagina", as: :minha_pagina
  get "meus_dados" => "users#dados_api", as: :meus_dados
  get "password" => "users#password", as: :minha_senha
  get "senha_sucesso" => "users#senha_sucesso", as: :senha_sucesso
  post "password_change" => "users#password_change"

  authenticated :user do
    root "users#minha_pagina"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  scope "/admin" do
    resources :users
  end

end

app/models/fake_secad.rb
# == Schema Information
#
# Table name: fake_secads
#
#  id                 :integer          not null, primary key
#  agencia            :string
#  bairro             :string
#  banco              :string
#  cargo              :string
#  cep                :string
#  cidade             :string
#  conta              :string
#  data_admissao      :date
#  data_base_ferias   :date
#  data_demissao      :date
#  data_fim_contrato  :date
#  data_nascimento    :date
#  dtfim_ferias       :date
#  dtini_ferias       :date
#  endereco           :string
#  escolaridade       :string
#  funcao             :string
#  gratificacao       :string
#  matricula          :string
#  numfunc            :string
#  numrg              :string
#  numvinc            :string
#  orgao              :string(255)
#  orgaorg            :string
#  pis                :string
#  referencia_cargo_  :string
#  referencia_funcao_ :string
#  salario            :string
#  sexo               :string
#  situacao           :string
#  situacao_ferias    :string
#  telefone           :string
#  tipo_vinculo       :string
#  uf                 :string
#  ufrg               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  entity_id          :integer
#  user_id            :integer
#
# Indexes
#
#  index_fake_secads_on_entity_id  (entity_id)
#  index_fake_secads_on_user_id    (user_id)
#

class FakeSecad < ActiveRecord::Base
  belongs_to :user
  belongs_to :entity, primary_key: 'id_unid_gestora'

  def json_w_orgao
  	JSON.parse(self.to_json).merge(
  		{
  			cod_orgao: entity.id_unid_gestora, 
  			orgao: entity.to_s, 
  			sigla_orgao: entity.sigla,
  			cnpj_orgao: nil
  		}
  	)
  end

  def nome
    user.name
  end
end

app/controllers/fake_secads_controller.rb
class FakeSecadsController < ApplicationController
  before_action :set_fake_secad, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @fake_secads = FakeSecad.all
    respond_with(@fake_secads)
  end

  def show
    respond_with(@fake_secad)
  end

  def new
    @fake_secad = FakeSecad.new
    respond_with(@fake_secad)
  end

  def edit
  end

  def create
    @fake_secad = FakeSecad.new(fake_secad_params)
    @fake_secad.save
    respond_with(@fake_secad)
  end

  def update
    @fake_secad.update(fake_secad_params)
    respond_with(@fake_secad)
  end

  def destroy
    @fake_secad.destroy
    respond_with(@fake_secad)
  end

  private
    def set_fake_secad
      @fake_secad = FakeSecad.find(params[:id])
    end

    def fake_secad_params
      params.require(:fake_secad).permit(:user_id, :entity_id, :matricula, :numfunc, :numvinc, :sexo, :numrg, :orgaorg, :ufrg, :data_admissao, :telefone, :endereco, :bairro, :cidade, :cep, :uf, :data_nascimento, :data_base_ferias, :cargo, :funcao, :salario, :gratificacao, :tipo_vinculo, :data_demissao, :data_fim_contrato, :escolaridade, :situacao, :referencia_cargo_, :pis, :referencia_funcao_, :dtini_ferias, :dtfim_ferias, :agencia, :conta, :banco, :situacao_ferias)
    end
end

app/helpers/fake_secads_helper.rb
module FakeSecadsHelper
end

app/views/fake_secads/_form.html.erb
<%= form_for(@fake_secad) do |f| %>
  <% if @fake_secad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fake_secad.errors.count, "error") %> prohibited this fake_secad from being saved:</h2>

      <ul>
      <% @fake_secad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= fs.label :user_id %><br>
    <%= fs.text_field :user_id %>
  </div>
  <div class="field">
    <%= fs.label :entity_id %><br>
    <%= fs.text_field :entity_id %>
  </div>
  <div class="field">
    <%= fs.label :matricula %><br>
    <%= fs.text_field :matricula %>
  </div>
  <div class="field">
    <%= fs.label :numfunc %><br>
    <%= fs.text_field :numfunc %>
  </div>
  <div class="field">
    <%= fs.label :numvinc %><br>
    <%= fs.text_field :numvinc %>
  </div>
  <div class="field">
    <%= fs.label :sexo %><br>
    <%= fs.text_field :sexo %>
  </div>
  <div class="field">
    <%= fs.label :numrg %><br>
    <%= fs.text_field :numrg %>
  </div>
  <div class="field">
    <%= fs.label :orgaorg %><br>
    <%= fs.text_field :orgaorg %>
  </div>
  <div class="field">
    <%= fs.label :ufrg %><br>
    <%= fs.text_field :ufrg %>
  </div>
  <div class="field">
    <%= fs.label :data_admissao %><br>
    <%= fs.date_select :data_admissao %>
  </div>
  <div class="field">
    <%= fs.label :telefone %><br>
    <%= fs.text_field :telefone %>
  </div>
  <div class="field">
    <%= fs.label :endereco %><br>
    <%= fs.text_field :endereco %>
  </div>
  <div class="field">
    <%= fs.label :bairro %><br>
    <%= fs.text_field :bairro %>
  </div>
  <div class="field">
    <%= fs.label :cidade %><br>
    <%= fs.text_field :cidade %>
  </div>
  <div class="field">
    <%= fs.label :cep %><br>
    <%= fs.text_field :cep %>
  </div>
  <div class="field">
    <%= fs.label :uf %><br>
    <%= fs.text_field :uf %>
  </div>
  <div class="field">
    <%= fs.label :data_nascimento %><br>
    <%= fs.date_select :data_nascimento %>
  </div>
  <div class="field">
    <%= fs.label :data_base_ferias %><br>
    <%= fs.date_select :data_base_ferias %>
  </div>
  <div class="field">
    <%= fs.label :cargo %><br>
    <%= fs.text_field :cargo %>
  </div>
  <div class="field">
    <%= fs.label :funcao %><br>
    <%= fs.text_field :funcao %>
  </div>
  <div class="field">
    <%= fs.label :salario %><br>
    <%= fs.text_field :salario %>
  </div>
  <div class="field">
    <%= fs.label :gratificacao %><br>
    <%= fs.text_field :gratificacao %>
  </div>
  <div class="field">
    <%= fs.label :tipo_vinculo %><br>
    <%= fs.text_field :tipo_vinculo %>
  </div>
  <div class="field">
    <%= fs.label :data_demissao %><br>
    <%= fs.date_select :data_demissao %>
  </div>
  <div class="field">
    <%= fs.label :data_fim_contrato %><br>
    <%= fs.date_select :data_fim_contrato %>
  </div>
  <div class="field">
    <%= fs.label :escolaridade %><br>
    <%= fs.text_field :escolaridade %>
  </div>
  <div class="field">
    <%= fs.label :situacao %><br>
    <%= fs.text_field :situacao %>
  </div>
  <div class="field">
    <%= fs.label :referencia_cargo_ %><br>
    <%= fs.text_field :referencia_cargo_ %>
  </div>
  <div class="field">
    <%= fs.label :pis %><br>
    <%= fs.text_field :pis %>
  </div>
  <div class="field">
    <%= fs.label :referencia_funcao_ %><br>
    <%= fs.text_field :referencia_funcao_ %>
  </div>
  <div class="field">
    <%= fs.label :dtini_ferias %><br>
    <%= fs.date_select :dtini_ferias %>
  </div>
  <div class="field">
    <%= fs.label :dtfim_ferias %><br>
    <%= fs.date_select :dtfim_ferias %>
  </div>
  <div class="field">
    <%= fs.label :agencia %><br>
    <%= fs.text_field :agencia %>
  </div>
  <div class="field">
    <%= fs.label :conta %><br>
    <%= fs.text_field :conta %>
  </div>
  <div class="field">
    <%= fs.label :banco %><br>
    <%= fs.text_field :banco %>
  </div>
  <div class="field">
    <%= fs.label :situacao_ferias %><br>
    <%= fs.text_field :situacao_ferias %>
  </div>
  <div class="actions">
    <%= fs.submit %>
  </div>
<% end %>

app/views/fake_secads/edit.html.erb
<h1>Editing fake_secad</h1>

<%= render 'form' %>

<%= link_to 'Show', @fake_secad %> |
<%= link_to 'Back', fake_secads_path %>

app/views/fake_secads/index.html.erb
<h1>Listing fake_secads</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Entity</th>
      <th>Matricula</th>
      <th>Numfunc</th>
      <th>Numvinc</th>
      <th>Sexo</th>
      <th>Numrg</th>
      <th>Orgaorg</th>
      <th>Ufrg</th>
      <th>Data admissao</th>
      <th>Telefone</th>
      <th>Endereco</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Cep</th>
      <th>Uf</th>
      <th>Data nascimento</th>
      <th>Data base ferias</th>
      <th>Cargo</th>
      <th>Funcao</th>
      <th>Salario</th>
      <th>Gratificacao</th>
      <th>Tipo vinculo</th>
      <th>Data demissao</th>
      <th>Data fim contrato</th>
      <th>Escolaridade</th>
      <th>Situacao</th>
      <th>Referencia cargo </th>
      <th>Pis</th>
      <th>Referencia funcao </th>
      <th>Dtini ferias</th>
      <th>Dtfim ferias</th>
      <th>Agencia</th>
      <th>Conta</th>
      <th>Banco</th>
      <th>Situacao ferias</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fake_secads.each do |fake_secad| %>
      <tr>
        <td><%= fake_secad.user %></td>
        <td><%= fake_secad.entity %></td>
        <td><%= fake_secad.matricula %></td>
        <td><%= fake_secad.numfunc %></td>
        <td><%= fake_secad.numvinc %></td>
        <td><%= fake_secad.sexo %></td>
        <td><%= fake_secad.numrg %></td>
        <td><%= fake_secad.orgaorg %></td>
        <td><%= fake_secad.ufrg %></td>
        <td><%= fake_secad.data_admissao %></td>
        <td><%= fake_secad.telefone %></td>
        <td><%= fake_secad.endereco %></td>
        <td><%= fake_secad.bairro %></td>
        <td><%= fake_secad.cidade %></td>
        <td><%= fake_secad.cep %></td>
        <td><%= fake_secad.uf %></td>
        <td><%= fake_secad.data_nascimento %></td>
        <td><%= fake_secad.data_base_ferias %></td>
        <td><%= fake_secad.cargo %></td>
        <td><%= fake_secad.funcao %></td>
        <td><%= fake_secad.salario %></td>
        <td><%= fake_secad.gratificacao %></td>
        <td><%= fake_secad.tipo_vinculo %></td>
        <td><%= fake_secad.data_demissao %></td>
        <td><%= fake_secad.data_fim_contrato %></td>
        <td><%= fake_secad.escolaridade %></td>
        <td><%= fake_secad.situacao %></td>
        <td><%= fake_secad.referencia_cargo_ %></td>
        <td><%= fake_secad.pis %></td>
        <td><%= fake_secad.referencia_funcao_ %></td>
        <td><%= fake_secad.dtini_ferias %></td>
        <td><%= fake_secad.dtfim_ferias %></td>
        <td><%= fake_secad.agencia %></td>
        <td><%= fake_secad.conta %></td>
        <td><%= fake_secad.banco %></td>
        <td><%= fake_secad.situacao_ferias %></td>
        <td><%= link_to 'Show', fake_secad %></td>
        <td><%= link_to 'Edit', edit_fake_secad_path(fake_secad) %></td>
        <td><%= link_to 'Destroy', fake_secad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fake secad', new_fake_secad_path %>

app/views/fake_secads/new.html.erb
<h1>New fake_secad</h1>

<%= render 'form' %>

<%= link_to 'Back', fake_secads_path %>

app/views/fake_secads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @fake_secad.user %>
</p>

<p>
  <strong>Entity:</strong>
  <%= @fake_secad.entity %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @fake_secad.matricula %>
</p>

<p>
  <strong>Numfunc:</strong>
  <%= @fake_secad.numfunc %>
</p>

<p>
  <strong>Numvinc:</strong>
  <%= @fake_secad.numvinc %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @fake_secad.sexo %>
</p>

<p>
  <strong>Numrg:</strong>
  <%= @fake_secad.numrg %>
</p>

<p>
  <strong>Orgaorg:</strong>
  <%= @fake_secad.orgaorg %>
</p>

<p>
  <strong>Ufrg:</strong>
  <%= @fake_secad.ufrg %>
</p>

<p>
  <strong>Data admissao:</strong>
  <%= @fake_secad.data_admissao %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @fake_secad.telefone %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @fake_secad.endereco %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @fake_secad.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @fake_secad.cidade %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @fake_secad.cep %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @fake_secad.uf %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @fake_secad.data_nascimento %>
</p>

<p>
  <strong>Data base ferias:</strong>
  <%= @fake_secad.data_base_ferias %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @fake_secad.cargo %>
</p>

<p>
  <strong>Funcao:</strong>
  <%= @fake_secad.funcao %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @fake_secad.salario %>
</p>

<p>
  <strong>Gratificacao:</strong>
  <%= @fake_secad.gratificacao %>
</p>

<p>
  <strong>Tipo vinculo:</strong>
  <%= @fake_secad.tipo_vinculo %>
</p>

<p>
  <strong>Data demissao:</strong>
  <%= @fake_secad.data_demissao %>
</p>

<p>
  <strong>Data fim contrato:</strong>
  <%= @fake_secad.data_fim_contrato %>
</p>

<p>
  <strong>Escolaridade:</strong>
  <%= @fake_secad.escolaridade %>
</p>

<p>
  <strong>Situacao:</strong>
  <%= @fake_secad.situacao %>
</p>

<p>
  <strong>Referencia cargo :</strong>
  <%= @fake_secad.referencia_cargo_ %>
</p>

<p>
  <strong>Pis:</strong>
  <%= @fake_secad.pis %>
</p>

<p>
  <strong>Referencia funcao :</strong>
  <%= @fake_secad.referencia_funcao_ %>
</p>

<p>
  <strong>Dtini ferias:</strong>
  <%= @fake_secad.dtini_ferias %>
</p>

<p>
  <strong>Dtfim ferias:</strong>
  <%= @fake_secad.dtfim_ferias %>
</p>

<p>
  <strong>Agencia:</strong>
  <%= @fake_secad.agencia %>
</p>

<p>
  <strong>Conta:</strong>
  <%= @fake_secad.conta %>
</p>

<p>
  <strong>Banco:</strong>
  <%= @fake_secad.banco %>
</p>

<p>
  <strong>Situacao ferias:</strong>
  <%= @fake_secad.situacao_ferias %>
</p>

<%= link_to 'Edit', edit_fake_secad_path(@fake_secad) %> |
<%= link_to 'Back', fake_secads_path %>