config/routes.rb
Rails.application.routes.draw do
  resources :employees
  get 'alerts/index', as: :alert

  resources :fake_secads

  get 'api/me'
  get 'api/me/profile' => "api#profile"
  get 'api/departments_by_ug'
  get 'api/servers_by_ug'
  post 'api/sign_by_password'
  post 'api/get_token'

  use_doorkeeper

  devise_for :users
  resources :users do
    member do
      patch "change_avatar"
    end
    collection do
      get "clear_coockie"
      post "autenticar_service"
      get "login_secad"
    end
  end

  get "minha_pagina" => "users#minha_pagina", as: :minha_pagina
  get "meus_dados" => "users#dados_api", as: :meus_dados
  get "password" => "users#password", as: :minha_senha
  get "senha_sucesso" => "users#senha_sucesso", as: :senha_sucesso
  post "password_change" => "users#password_change"

  authenticated :user do
    root "users#minha_pagina"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  scope "/admin" do
    resources :users
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  admin                  :boolean
#  bypass_validation      :boolean
#  cloudinary_code        :string
#  cpf                    :string
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  matricula              :string
#  name                   :string
#  photo                  :text
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
	require 'openssl'
	require 'base64'
	require 'rest-client'
	extend Enumerize

	has_one :fake_secad

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable

	validate :validate_secad
	validates :cpf, :matricula, presence: true
	validates :cpf, uniqueness: true
	before_validation :set_name
	before_validation :check_bypass, on: :create

	accepts_nested_attributes_for :fake_secad

	enumerize :perfil, in: [:admin, :suporte, :servidor], predicates: true, default: :servidor

	attr_accessor :login

	default_scope -> {where(bypass_validation: [nil, true])}

	def self.base64_to_hex(base64_string)
		base64_string.scan(/.{4}/).map do |b|
			b.unpack('m0').first.unpack('H*')
		end.join
	end

	def self.teste(msg)

	end

	def self.decrypt(msg)
		#begin
			cipher = OpenSSL::Cipher.new('AES-128-ECB')
			cipher.decrypt()

			cipher.key = "At1_SgF@gds2020#" #"1234567890098765"
			#converte o hexadecimal em base64
			hex_2_64 = [[msg].pack("H*")].pack("m0")
			tempkey = Base64.decode64(hex_2_64)
			crypt = cipher.update(tempkey) + cipher.final
			#crypt << cipher.final()
			return crypt
			#rescue Exception => exc
			#puts ("Message for the decryption log file for message #{msg} = #{exc.message}")
			#end
	end

	def profile
		secad =  retornaDadosServidor #Secad.where(cpf: self.cpf).last #Employee.find_by_cpf(self.cpf)
		if secad.blank?
			return fake_secad
		end
		secad
	end

	#Busca os dados do servidor na EstruturaApi
	def retornaDadosServidor
		
		rest = RestClient.get 'http://estrutura.ati.to.gov.br/departments/retornaDadosServidor', {params: {cpf: self.cpf, token: "314abca0b4d1b6c5cb336fa1bbc09c8e6a28a0733fcd068b5281f4819488bb7d"}}
		begin
			if rest.present?
				if JSON.parse(rest).size == 2
					JSON.parse(rest)[0].with_indifferent_access
				else
					return JSON.parse(rest).with_indifferent_access
				end
			else
				{}
			end
		rescue StandardError => e
			puts e.message  
  		puts e.backtrace.inspect  
		end
	end

	def can_fake_secad
		Secad.find_by_cpf(self.cpf).blank?
	end

	def siato
		Siato.find_by_cpf(self.cpf)
	end

	def departamento
		#if siato.present? and siato.id_departamento.present?
			#return Department.find(siato.id_departamento)
		#end
		retorno = {}

		begin
			rest = RestClient.get 'http://estrutura.ati.to.gov.br/departments/departamentoServidor', {params: {cpf: self.cpf, token: "314abca0b4d1b6c5cb336fa1bbc09c8e6a28a0733fcd068b5281f4819488bb7d"}}
			if rest.present?
				retorno = JSON.parse(rest)
			end
		rescue
			retorno = {}
		end
		retorno
	end

	def boss?
		if departamento.present?			
			return departamento.id_servidor == siato.id_servidor
		end
		false
	end

	def responsaveis_departamento
		dep = departamento
		if dep.present?
			begin
				responsaveis = RestClient.get 'http://estrutura.ati.to.gov.br/departments/responsaveisAtivos', {params: {codigo: dep[0]["department_id"], token: "314abca0b4d1b6c5cb336fa1bbc09c8e6a28a0733fcd068b5281f4819488bb7d"}}
				JSON.parse(responsaveis)
			rescue
				{}
			end
		else
			{}
		end
	end

	def chefe_imediato
		dep = departamento
		if dep.present?
			begin
				chefe1 = Siato.find_by_id_servidor(departamento.id_servidor)
				if chefe1.cpf == self.cpf
					next_department = Department.find(departamento.id_departamento_superior)
					return Siato.find_by_id_servidor(next_department.id_servidor)
				end
				return chefe1
			rescue
				{}
			end
		end
		{}
	end

	def chefe_suplente
		begin
			if departamento.present?
				chefe_imediato = Siato.find_by_id_servidor(departamento.id_servidor)
				chefe1 = Siato.find_by_id_servidor(departamento.id_servidor_suplente)
				if chefe_imediato.cpf == self.cpf
					next_department = Department.find(departamento.id_departamento_superior)
					return Siato.find_by_id_servidor(next_department.id_servidor_suplente)
				end
				return chefe1
			end
		rescue
		end
		{}
	end

	def set_name
		puts "cpf - #{self.cpf}"
        if !can_fake_secad
            begin
            self.name = self.profile["nome"]
            rescue
            end
		end
	end

	def name_top
		if self.name.present?
			self.name.split(" ")[0]
		else
			"Usuário"
		end		
	end

	def check_bypass
		if bypass_mail?
			self.bypass_validation = false
			self.name = 'Usuário Unitins'
			self.fake_secad = FakeSecad.new(
				 entity_id: 1001
			)
		end
	end

	def bypass_config
		[
				{mail: '@unitins.br', entity: '1001', cargo: 'unitins' }
		]
	end

	def bypass_mail?
		bypass_config.any? { |word| self.email.include?(word[:mail]) }
	end

	def validate_secad
		if !bypass_mail?
			if profile.blank?
					errors.add(:profile, "Você não possui cadastro ativo na SECAD")
			else
					if fake_secad.blank? and profile["numfunca"] != self.matricula.to_i
						errors.add(:profile, "Os dados cadastrados não estão de acordo com os dados da SECAD.")
					end
			end
		end
	end

	def active?
		profile.present?
	end


	def photo_url
		if self.photo.present?
			self.photo.sub! 'http://', 'https://'
		else
			'http://toauth.ati.to.gov.br/mosaicpro/images/default-avatar.png'
		end
	end

	def self.find_for_database_authentication(warden_conditions)
		conditions = warden_conditions.dup
		if login = conditions.delete(:login)
			where(conditions.to_h).where(["lower(cpf) = :value OR lower(email) = :value", { :value => login.downcase }]).first
		else
			where(conditions.to_h).first
		end
	end

	def cordinates
		Geocoder.coordinates("#{profile["endereco"]}, #{profile["cidade"]}, Tocantins, Brasil")
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :verify_authenticity_token, only:[:autenticar_service, :login_secad]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :change_avatar]
  before_action :authenticate_user!, except: [:senha_sucesso , :clear_coockie,:autenticar_service, :login_secad]
  #before_action :allow_iframe, :set_headers
  load_and_authorize_resource except:[:autenticar_service, :login_secad]


  respond_to :html, :json

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET, POST'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = '*'
  end

  #Método que realiza o login do usuário passado pelo portal do servidor
  def login_secad
    #https://www.devglan.com/online-tools/aes-encryption-decryption
    cpf = User.decrypt(params[:data])
    user = User.find_by_cpf(cpf)
    if user.present?
      sign_in(user)
      redirect_to "http://sgf-hom.ati.to.gov.br"
      return
    else
      user = User.new(cpf: cpf)
      dados = user.retornaDadosServidor
      if dados.present?
        user.email = dados[:email]
        user.matricula = "#{dados[:numfunca]}-#{dados[:numvinc]}"
        user.name = dados[:nome]
        password = rand(99999999)
        user.password = password
        user.password_confirmation = password
        if user.save
          sign_in(user)
          redirect_to "http://sgf-hom.ati.to.gov.br"
          return
        else
          redirect_to root_path, notice: "Erro ao criar usuário!"
          return
        end
      else
        redirect_to root_path, notice: "Servidor não encontrado!"
        return
      end
    end

  end

  #Método para autenticar via serviço
  def autenticar_service

    user = User.find_by(cpf: params[:cpf])
    #binding.pry
    if user.present?
      if user.valid_password? params[:password]
        render json: {status: "OK", user: user.profile.reject{ |p| p["biometria"]}, data_hora: DateTime.now}
      else
        render json: {status: "ERROR", mensagem: "Dados de acesso inválidos."}
      end
    else
      render json: {status: "ERROR", mensagem: "Servidor não encontrado."}
    end

  end

  def index
    @q = User.unscoped.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(10)
    respond_with(@users)
  end

  def minha_pagina
    @user = current_user
    render :show, layout: "material"
  end

  def show
    render layout: "material"
  end

  def new
    @user = User.new
    @user.fake_secad = FakeSecad.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save(validates: false)
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  def password
  end

  def password_change
    user = current_user
    user.password = params[:password]
    user.password_confirmation = params[:password_confirmation]
    if user.save
      redirect_to senha_sucesso_path
    else
      redirect_to minha_senha_path, :flash => { :alert => "Não foi possível salvar sua senha, tente novamente." }
    end
  end

  def senha_sucesso
  end

  def change_avatar
    if params[:user][:photo].present?
      if @user.photo.present?
        code_antigo = @user.cloudinary_code || "toauth_avatar_#{@user.cpf}"
        Cloudinary::Uploader.destroy(code_antigo)
      end
      @user.cloudinary_code = "toauth_avatar_#{@user.cpf}_#{DateTime.now.to_i}"
      Cloudinary::Uploader.upload(params[:user][:photo], public_id: "#{@user.cloudinary_code}", invalidate: true)
      @user.photo = Cloudinary::Utils.cloudinary_url("#{@user.cloudinary_code}", width: 100, height: 100, crop: :fill, gravity: :face)
      @user.save
    end 
    redirect_to root_path
  end

  def clear_coockie
    cookies.delete :user_id
    redirect_to "/"
  end

  private
    def set_user
      @user = User.unscoped.find(params[:id])
    end

    def user_params
      user_params = params.require(:user).permit(
        :name, :cpf, :matricula,:password, :photo, :perfil, :bypass_validation,
        fake_secad_attributes:[
         :id, :user_id, :entity_id, :matricula, :numfunc, :numvinc, :sexo, 
         :numrg, :orgaorg, :ufrg, :data_admissao, :telefone, :endereco, :bairro,
         :cidade, :cep, :uf, :data_nascimento, :data_base_ferias, :cargo, 
         :funcao, :salario, :gratificacao, :tipo_vinculo, :data_demissao, 
         :data_fim_contrato, :escolaridade, :situacao, :referencia_cargo_, 
         :pis, :referencia_funcao_, :dtini_ferias, :dtfim_ferias, :agencia, 
         :conta, :banco, :situacao_ferias
        ]
      )

      user_params.delete(:password) unless user_params[:password].present?
      user_params.delete(:password_confirmation) unless user_params[:password_confirmation].present?

      user_params
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= content_for :title do "Usuarios"  end %>
<%= content_for :icon_page do "fa-group"  end %>
<%= content_for :botao_add do  %>
<%= link_to "Ver Todos", users_path, class:"btn btn-info" %>
<% end %>
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>



<div class="row">
  <div class="col-md-6">
    <div class="widget media margin-none bg-gray ">
      <a class="pull-left bg-info innerAll text-center text-white"><i class="fa icon-user-2 fa-5x"></i></a>
      <div class="media-body innerAll">
        <h4 class="media-heading innerT"> Configurando Pessoa</h4>                     
        <p>Dados pessoais do usuário.</p>
      </div>
      <div class="widget-body bg-white">
        <div class="field">
          <%= f.label :name, "Nome" %>
          <%= f.text_field :name, class:"form-control", required: true %>
          <p>&nbsp;</p>
        </div>
        <div class="field">
          <%= f.label :cpf %>
          <%= f.text_field :cpf, class:"form-control", required: true %>
          <p>&nbsp;</p>
        </div>
        <div class="field">
          <%= f.label :matricula %>
          <%= f.text_field :matricula, class:"form-control", required: true %>
          <p>&nbsp;</p>
          <%= f.file_field :photo  %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="widget media margin-none bg-gray ">
      <a class="pull-left bg-info innerAll text-center text-white"><i class="fa icon-car-key fa-5x"></i></a>
      <div class="media-body innerAll">
        <h4 class="media-heading innerT"> Configurando Acesso</h4>                     
        <p>Credenciais de acesso ao Sistema.</p>
      </div>
      <div class="widget-body bg-white">
        <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email , class:"form-control", required: true %>
          <p>&nbsp;</p>
        </div>
        <div class="field">
          <%= f.label :perfil, "Perfis" %>
          <%= f.select :perfil,
                       options_for_select(User.perfil.options, @user.perfil),
                       {},
                       {class: 'form-control'} %>
          <p>&nbsp;</p>
        </div>
        <div class="field">
          <%= f.label :password, "Senha" %>
          <%= f.password_field :password , class:"form-control" %>
          <p>&nbsp;</p>
        </div>
        <div class="field">
          <%= f.label :password_confirmation, "Confirme a Senha" %>
          <%= f.password_field :password_confirmation , class:"form-control"   %>
          <p>&nbsp;</p>
        </div>
      </div>  
    </div>
  </div>
</div>
<%= f.fields_for :fake_secad do |fs|  %>
<p>&nbsp;</p>
<div class="row">
  <div class="col-md-12">
    <div class="widget media margin-none bg-gray ">
      <a class="pull-left bg-info innerAll text-center text-white"><i class="fa icon-user-2 fa-5x"></i></a>
      <div class="media-body innerAll">
        <h4 class="media-heading innerT"> Configurando Dados SECAD Manualmente</h4>                     
        <p>Obrigatório para quem não está na tabela da SECAD.</p>
      </div>
      <div class="widget-body bg-white">
        <div>
          <%= f.label :bypass_validation, "Autorizar Bypass Secad" %>
          <%= f.check_box :bypass_validation , class:"form-control"   %>
          <p>&nbsp;</p>
        </div>
        <div class="field">
          <%= fs.label :entity_id %><br>
          <%= fs.text_field :entity_id , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :matricula %><br>
          <%= fs.text_field :matricula , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :numfunc %><br>
          <%= fs.text_field :numfunc , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :numvinc %><br>
          <%= fs.text_field :numvinc , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :sexo %><br>
          <%= fs.text_field :sexo , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :numrg %><br>
          <%= fs.text_field :numrg , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :orgaorg %><br>
          <%= fs.text_field :orgaorg , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :ufrg %><br>
          <%= fs.text_field :ufrg , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :data_admissao %><br>
          <%= fs.date_select :data_admissao, class:"form-control" %>
        </div>
        <div class="field">
          <%= fs.label :telefone %><br>
          <%= fs.text_field :telefone , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :endereco %><br>
          <%= fs.text_field :endereco , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :bairro %><br>
          <%= fs.text_field :bairro , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :cidade %><br>
          <%= fs.text_field :cidade , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :cep %><br>
          <%= fs.text_field :cep , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :uf %><br>
          <%= fs.text_field :uf , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :data_nascimento %><br>
          <%= fs.date_select :data_nascimento, class:"form-control" %>
        </div>
        <div class="field">
          <%= fs.label :data_base_ferias %><br>
          <%= fs.date_select :data_base_ferias, class:"form-control" %>
        </div>
        <div class="field">
          <%= fs.label :cargo %><br>
          <%= fs.text_field :cargo , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :funcao %><br>
          <%= fs.text_field :funcao , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :salario %><br>
          <%= fs.text_field :salario , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :gratificacao %><br>
          <%= fs.text_field :gratificacao , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :tipo_vinculo %><br>
          <%= fs.text_field :tipo_vinculo , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :data_demissao %><br>
          <%= fs.date_select :data_demissao, class:"form-control" %>
        </div>
        <div class="field">
          <%= fs.label :data_fim_contrato %><br>
          <%= fs.date_select :data_fim_contrato, class:"form-control" %>
        </div>
        <div class="field">
          <%= fs.label :escolaridade %><br>
          <%= fs.text_field :escolaridade , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :situacao %><br>
          <%= fs.text_field :situacao , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :referencia_cargo_ %><br>
          <%= fs.text_field :referencia_cargo_ , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :pis %><br>
          <%= fs.text_field :pis , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :referencia_funcao_ %><br>
          <%= fs.text_field :referencia_funcao_ , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :dtini_ferias %><br>
          <%= fs.date_select :dtini_ferias, class:"form-control" %>
        </div>
        <div class="field">
          <%= fs.label :dtfim_ferias %><br>
          <%= fs.date_select :dtfim_ferias, class:"form-control" %>
        </div>
        <div class="field">
          <%= fs.label :agencia %><br>
          <%= fs.text_field :agencia , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :conta %><br>
          <%= fs.text_field :conta , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :banco %><br>
          <%= fs.text_field :banco , class:"form-control"%>
        </div>
        <div class="field">
          <%= fs.label :situacao_ferias %><br>
          <%= fs.text_field :situacao_ferias , class:"form-control"%>
        </div>

      </div>
    </div>
  </div>
</div>
<% end %>
<p>&nbsp;</p>
<div class="col-md-12 innerAll inner-2x">   
  <%= f.submit "Salvar Usuario", class:"btn btn-lg btn-success btn-block" %>  
</div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<%= content_for :title do "Usuáriosss" end %>
<%= content_for :icon_page do "fa-group"  end %>
<%= content_for :botao_add do  %>
  <%= link_to "Novo", new_user_path, class:"btn btn-info" %>
<% end %>
<div class="widget">
  <!-- Category Heading -->
  <%= search_form_for @q do |f| %>
  <div class="input-group input-group-lg border-bottom">
    <span class="input-group-btn">
      <a href="" class="btn"><i class="fa fa-search text-muted"></i></a>
    </span>
    <%= f.text_field :name_or_email_or_cpf_or_matricula_cont, class: "form-control border-none", placeholder:"Pesquisa" %>
  </div>
  <% end %>
  <% @users.each do |user| %>

  <div class="bg-gray-hover overflow-hidden">
    <div class="row innerAll half border-bottom">

      <div class="col-sm-6 col-xs-8">
        <ul class="media-list margin-none">
          <li class="media">
            <a class="pull-left innerAll half " href="#">
              <span class="empty-photo">
                <i class="text-muted fa fa-user"></i>
              </span>
            </a>
            <div class="media-body">
              <div class="innerAll half">
                <h4 class="margin-none">                
                  <%= link_to user.name, user  %>               
                </h4>
                <div class="clearfix">                
                </div>
                <small class="margin-none text-muted"><%= user.cpf %> | <%= user.matricula %></small>
              </div>
            </div>

          </li>
        </ul>
      </div>


      <div class="col-sm-3 col-xs-hidden margin-none">
        <div class="innerAll half">
          <div class="media">
            <div class="media-body ">
              <span class="text-small">Desde</span>
              <div class="clearfix"></div>
              <small><%= user.created_at  %></small>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-3 col-xs-hidden margin-none">
        <div class="innerAll half">
          <div class="media">
            <div class="media-body ">
              <%= link_to :editar, edit_user_path(user), class:"btn btn-info" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<%= paginate @users %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/password.html.erb
<%= form_tag password_change_path, :method => 'post' do %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="widget media margin-none bg-gray ">
      <a class="pull-left bg-info innerAll text-center text-white"><i class="fa icon-car-key fa-5x"></i></a>
      <div class="media-body innerAll">
        <h4 class="media-heading innerT"> Minha Senha</h4>                     
        <p>Alterando minha senha no TOauth.</p>
      </div>
      <div class="widget-body bg-white">
        <div class="field">
          <%= label_tag :password, "Senha" %>
          <%= password_field_tag :password ,nil , class:"form-control" %>
          <p>&nbsp;</p>
        </div>
        <div class="field">
          <%= label_tag :password_confirmation, "Confirme a Senha" %>
          <%= password_field_tag :password_confirmation , nil ,class:"form-control"   %>
          <p>&nbsp;</p>
        </div>
        <div class="col-md-12 innerAll inner-2x">   
          <%= submit_tag "Salvar Senha", class:"btn btn-lg btn-success btn-block" %>  
        </div>
      </div>  
    </div>
  </div>
</div>
<p>&nbsp;</p>
<% end %>

app/views/users/senha_sucesso.html.erb
<div>
	<div class="error innerAll ">
        <div class="well text-center">
            <div class="center text-large innerAll">
                <i class="fa fa-5x fa-thumbs-o-up text-success "></i>
            </div>
            <h1 class="strong innerTB">Senha Alterada Com Sucesso!!!</h1>
            <div class="inerAll">
            	<%= link_to "Faça Login Novamente", new_user_session_path,  class:" btn btn-primary text-large "  %>          
            </div>
        </div>
    </div>
</div>