config/routes.rb
Rails.application.routes.draw do
  resources :employees
  get 'alerts/index', as: :alert

  resources :fake_secads

  get 'api/me'
  get 'api/me/profile' => "api#profile"
  get 'api/departments_by_ug'
  get 'api/servers_by_ug'
  post 'api/sign_by_password'
  post 'api/get_token'

  use_doorkeeper

  devise_for :users
  resources :users do
    member do
      patch "change_avatar"
    end
    collection do
      get "clear_coockie"
      post "autenticar_service"
      get "login_secad"
    end
  end

  get "minha_pagina" => "users#minha_pagina", as: :minha_pagina
  get "meus_dados" => "users#dados_api", as: :meus_dados
  get "password" => "users#password", as: :minha_senha
  get "senha_sucesso" => "users#senha_sucesso", as: :senha_sucesso
  post "password_change" => "users#password_change"

  authenticated :user do
    root "users#minha_pagina"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  scope "/admin" do
    resources :users
  end

end

app/views/layouts/_left_sidebar.html.erb
<aside id="left-sidebar-nav">
	<ul id="slide-out" class="side-nav fixed leftside-navigation">

		<% if user_signed_in? %>		
		<li class="user-details cyan darken-2">
			<div class="row">

				<div class="col col s4 m4 l4">
					<img src="<%= current_user.photo_url %>" alt="" class="circle responsive-img valign profile-image">
				</div>
				<div class="col col s8 m8 l8">
					<ul id="profile-dropdown" class="dropdown-content">
						<li><a href="/"><i class="mdi-action-face-unlock"></i> Perfil</a>
						</li>
						<li>
							<%= link_to minha_senha_path do %>
							<i class="mdi-communication-vpn-key"></i> Senha
							<% end %> 
						</li>
						<li><a href="<%= destroy_user_session_path  %>"><i class="mdi-hardware-keyboard-tab"></i> Logout</a>
						</li>
					</ul>
					<a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown"><%= current_user.name.split(' ')[0] %><i class="mdi-navigation-arrow-drop-down right"></i></a>
					<p class="user-roal"><%= current_user.cpf  %></p>
				</div>
			</div>
		</li>
		<% end %>
		<li class="bold">
			<a href="http://gestores.seplan.to.gov.br" class="waves-effect waves-cyan">
				<i class="mdi-action-account-child"></i> Grupo Executivo
			</a>
		</li>
		<li class="bold">
			<a href="http://oquena.seplan.to.gov.br" class="waves-effect waves-cyan">
				<i class="mdi-action-verified-user"></i> Oquena
			</a>
		</li>
		<li class="bold">
			<a href="http://www.siato.to.gov.br" class="waves-effect waves-cyan">
				<i class="mdi-av-my-library-books"></i> Siato
			</a>
		</li>

		<li class="bold">
			<a href="http://sgd.to.gov.br/" class="waves-effect waves-cyan">
				<i class="mdi-editor-insert-drive-file"></i> SGD
			</a>
		</li>
    <li class="bold">
      <a href="http://planejamento.monitora.to.gov.br" class="waves-effect waves-cyan">
        <i class="mdi-action-group-work"></i> Planeja
      </a>
    </li>
    <li class="bold">
      <a href="http://www.servicos.to.gov.br/admin" class="waves-effect waves-cyan">
        <i class="mdi-action-help"></i> Portal de Serviços
      </a>
    </li>
	</ul>
	<a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
</aside>

app/views/layouts/_menu.html.erb
<ul class="nav navbar-nav">
    <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="">Usuários <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li>
                <%= link_to "Listar", users_path %>
            </li>
            <li>
                <%= link_to "Novo", new_user_path %>
            </li>
        </ul>
    </li>
    <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="">Aplicações <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li>
                <%= link_to "Listar", oauth_applications_path %>
            </li>
        </ul>
    </li>
</ul>

app/views/layouts/_right_sidebar.html.erb
<aside id="right-sidebar-nav">
	<ul id="chat-out" class="side-nav rightside-navigation">
		<li class="li-hover">
			<a href="/materialize/#" data-activates="chat-out" class="chat-close-collapse right"><i class="mdi-navigation-close"></i></a>
			<div id="right-search" class="row">
				<form class="col s12">
					<div class="input-field">
						<i class="mdi-action-search prefix"></i>
						<input id="icon_prefix" type="text" class="validate">
						<label for="icon_prefix">Search</label>
					</div>
				</form>
			</div>
		</li>
		<li class="li-hover">
			<ul class="chat-collapsible" data-collapsible="expandable">
				<li>
					<div class="collapsible-header teal white-text active"><i class="mdi-social-whatshot"></i>Recent Activity</div>
					<div class="collapsible-body recent-activity">
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="mdi-action-add-shopping-cart"></i>
							</div>
							<div class="col s9 recent-activity-list-text">
								<a href="/materialize/#">just now</a>
								<p>Jim Doe Purchased new equipments for zonal office.</p>
							</div>
						</div>
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="mdi-device-airplanemode-on"></i>
							</div>
							<div class="col s9 recent-activity-list-text">
								<a href="/materialize/#">Yesterday</a>
								<p>Your Next flight for USA will be on 15th August 2015.</p>
							</div>
						</div>
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="mdi-action-settings-voice"></i>
							</div>
							<div class="col s9 recent-activity-list-text">
								<a href="/materialize/#">5 Days Ago</a>
								<p>Natalya Parker Send you a voice mail for next conference.</p>
							</div>
						</div>
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="mdi-action-store"></i>
							</div>
							<div class="col s9 recent-activity-list-text">
								<a href="/materialize/#">Last Week</a>
								<p>Jessy Jay open a new store at S.G Road.</p>
							</div>
						</div>
						<div class="recent-activity-list chat-out-list row">
							<div class="col s3 recent-activity-list-icon"><i class="mdi-action-settings-voice"></i>
							</div>
							<div class="col s9 recent-activity-list-text">
								<a href="/materialize/#">5 Days Ago</a>
								<p>Natalya Parker Send you a voice mail for next conference.</p>
							</div>
						</div>
					</div>
				</li>
				<li>
					<div class="collapsible-header light-blue white-text active"><i class="mdi-editor-attach-money"></i>Sales Repoart</div>
					<div class="collapsible-body sales-repoart">
						<div class="sales-repoart-list  chat-out-list row">
							<div class="col s8">Target Salse</div>
							<div class="col s4"><span id="sales-line-1"></span>
							</div>
						</div>
						<div class="sales-repoart-list chat-out-list row">
							<div class="col s8">Payment Due</div>
							<div class="col s4"><span id="sales-bar-1"></span>
							</div>
						</div>
						<div class="sales-repoart-list chat-out-list row">
							<div class="col s8">Total Delivery</div>
							<div class="col s4"><span id="sales-line-2"></span>
							</div>
						</div>
						<div class="sales-repoart-list chat-out-list row">
							<div class="col s8">Total Progress</div>
							<div class="col s4"><span id="sales-bar-2"></span>
							</div>
						</div>
					</div>
				</li>
				<li>
					<div class="collapsible-header red white-text"><i class="mdi-action-stars"></i>Favorite Associates</div>
					<div class="collapsible-body favorite-associates">
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4"><img src="/materialize/images/avatar.jpg" alt="" class="circle responsive-img online-user valign profile-image">
							</div>
							<div class="col s8">
								<p>Eileen Sideways</p>
								<p class="place">Los Angeles, CA</p>
							</div>
						</div>
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4"><img src="/materialize/images/avatar.jpg" alt="" class="circle responsive-img online-user valign profile-image">
							</div>
							<div class="col s8">
								<p>Zaham Sindil</p>
								<p class="place">San Francisco, CA</p>
							</div>
						</div>
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4"><img src="/materialize/images/avatar.jpg" alt="" class="circle responsive-img offline-user valign profile-image">
							</div>
							<div class="col s8">
								<p>Renov Leongal</p>
								<p class="place">Cebu City, Philippines</p>
							</div>
						</div>
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4"><img src="/materialize/images/avatar.jpg" alt="" class="circle responsive-img online-user valign profile-image">
							</div>
							<div class="col s8">
								<p>Weno Carasbong</p>
								<p>Tokyo, Japan</p>
							</div>
						</div>
						<div class="favorite-associate-list chat-out-list row">
							<div class="col s4"><img src="/materialize/images/avatar.jpg" alt="" class="circle responsive-img offline-user valign profile-image">
							</div>
							<div class="col s8">
								<p>Nusja Nawancali</p>
								<p class="place">Bangkok, Thailand</p>
							</div>
						</div>
					</div>
				</li>
			</ul>
		</li>
	</ul>
	</aside

app/views/layouts/_topbar.html.erb
<header id="header" class="page-topbar">
		<!-- start header nav-->
		<div class="navbar-fixed">
			<nav class="cyan">
				<div class="nav-wrapper">                    

					<ul class="left">                      
						<li><h1 class="logo-wrapper"><a href="/" class="brand-logo darken-1">TOauth</a></h1></li>
					</ul>
					<ul class="right hide-on-med-and-down">                        
						<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
						</li>                      
					</ul>
				</div>
			</nav>
		</div>
		<!-- end header nav-->
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7 "> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8 "> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9 "> <![endif]-->
<!--[if gt IE 8]> <html class="ie "> <![endif]-->
<!--[if !IE]><!-->
<html class="">
<!-- <![endif]-->
<head>
    <title>TOauth</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- 
    **********************************************************
    In development, use the LESS files and the less.js compiler
    instead of the minified CSS loaded by default.
    **********************************************************
    <link rel="stylesheet/less" href="/mosaicpro/less/admin/module.admin.stylesheet-complete.sidebar_type.no-sidebar.less" />
-->
<!--[if lt IE 9]><link rel="stylesheet" href="/mosaicpro/components/library/bootstrap/css/bootstrap.min.css" /><![endif]-->
<link rel="stylesheet" href="/mosaicpro/css/admin/module.admin.stylesheet-complete.sidebar_type.no-sidebar.min.css"
/>  
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
      <script src="/mosaicpro/components/library/jquery/jquery.min.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
      <script src="/mosaicpro/components/library/jquery/jquery-migrate.min.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
      <script src="/mosaicpro/components/library/modernizr/modernizr.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
      <script src="/mosaicpro/components/plugins/less-js/less.min.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
      <script src="/mosaicpro/components/modules/admin/charts/flot/assets/lib/excanvas.js?v=v1.0.3-rc2"></script>
      <script src="/mosaicpro/components/plugins/browser/ie/ie.prototype.polyfill.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
      <script>
        if ( /*@cc_on!@*/ false && document.documentMode === 10)
        {
            document.documentElement.className += ' ie ie10';
        }
    </script>
    <style type="text/css">
        .navbar{
            background: url('http://barra.to.gov.br/imagens/bg_geometric.png');
        }
        #notyfy_container_top{
            top:50px;
        }
    </style>
</head>
<body class="">
    <!-- Main Container Fluid -->
    <div class="container-fluid menu-hidden">
        <!-- Content -->
        <div id="content">
        <% if user_signed_in? %> 
            <nav class="navbar hidden-print main " role="navigation">
                <div class="container">
                    <div class="navbar-header pull-left">
                        <div class="navbar-brand">
                            <a href="/">
                                <img src="https://barra.to.gov.br/imagens/logo.svg?1527695565" height="100%">
                            </a>
                        </div>
                        <button type="button" class="navbar-toggle padding-top-none" data-toggle="collapse"
                        data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <i class="fa fa-bars fa-2x text-muted-dark"></i>
                    </button>
                </div>
                <ul class="main pull-right ">
                                       
                    <li class="dropdown username">
                      <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="/mosaicpro/images/default-avatar.png" class="img-circle"
                        width="30" /><%= current_user.name_top  %>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <%= link_to minha_pagina_path, class:"glyphicons user" do %>
                                <i></i> Minha Página
                            <% end %>   
                        </li>
                        <li>
                            <%= link_to minha_senha_path, class:"glyphicons lock" do %>
                                <i></i> Alterar Senha
                            <% end %>   
                        </li>
                        <li>
                        
                        <%= link_to destroy_user_session_path, class:"glyphicons exit no-ajaxify" do %>
                            <i></i>Sair
                        <% end %>
                        </li>
                    </ul>
                </li>
            </ul>
            <div class="navbar-collapse collapse">
                <%= render 'layouts/menu' if current_user.admin? %>
            </div>
        </div>
        <!-- // END container -->
    </nav>
    <% end %>
    <!-- // END navbar -->
    <div class="container">
        <% if (yield :botao_add).present? %>        
            <div class="innerLR">
                <div class="pull-right hidden-print">
                  <div class="btn-group">
                    <%= yield :botao_add  %>
                    <%= yield :botoes %>
                </div>
            </div>
        <% end %>
        <% if  (yield :title).present? %>            
            <h2 class="margin-none <%= yield :title_class  %>"> <i class="fa fa-fw <%= yield :icon_page  %> text-muted"></i>&nbsp;<%= yield :title  %>
            </h2>        
        <% end %>
        <div class="clearfix"></div>
        <div class="row">
            <%= yield  %> 
        </div>
    </div>
</div>
<!-- // Content END -->
</div>
<!-- // Container END -->
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->
<div id="footer" class="hidden-print">
    <!--  Copyright Line -->
    <div class="copy">&copy; 2015 - TOauth desenvolvido por <a href="http://ati.to.gov.br">Agência de Tecnologia da Informação</a> - Direitos Reservados
    </div>
    <!--  End Copyright Line -->
</div>
<!-- // Footer END -->
</div>
<!-- // Main Container Fluid END -->
<!-- Global -->
<script data-id="App.Config">
    var App = {};
    var basePath = '',
        commonPath = '/mosaicpro/',
        rootPath = '../',
        DEV = false,
        componentsPath = '/mosaicpro/components/';
    var primaryColor = '#3695d5',
        dangerColor = '#b55151',
        successColor = '#609450',
        infoColor = '#4a8bc2',
        warningColor = '#ab7a4b',
        inverseColor = '#45484d';
    var themerPrimaryColor = primaryColor;

</script>


<script src="/mosaicpro/components/library/bootstrap/js/bootstrap.min.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/plugins/nicescroll/jquery.nicescroll.min.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/plugins/breakpoints/breakpoints.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/plugins/preload/pace/pace.min.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/plugins/preload/pace/preload.pace.init.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/core/js/animations.init.js?v=v1.0.3-rc2"></script>


<script src="/mosaicpro/components/modules/admin/charts/easy-pie/assets/lib/js/jquery.easy-pie-chart.js?v=v1.0.3-rc2"></script>
<script src="/mosaicpro/components/modules/admin/charts/easy-pie/assets/custom/easy-pie.init.js?v=v1.0.3-rc2"></script>
<script src="/mosaicpro/components/modules/admin/charts/sparkline/jquery.sparkline.min.js?v=v1.0.3-rc2"></script>
<script src="/mosaicpro/components/modules/admin/charts/sparkline/sparkline.init.js?v=v1.0.3-rc2"></script>
<script src="/mosaicpro/components/modules/admin/maps/vector/assets/lib/jquery-jvectormap-1.2.2.min.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/modules/admin/maps/vector/assets/lib/maps/jquery-jvectormap-world-mill-en.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/modules/admin/maps/vector/assets/custom/maps-vector.world-map-markers.init.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/core/js/core.init.js?v=v1.0.3-rc2"></script>
<script src="/mosaicpro/components/common/forms/elements/bootstrap-datepicker/assets/lib/js/bootstrap-datepicker.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/common/forms/elements/bootstrap-datepicker/assets/custom/js/bootstrap-datepicker.init.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/common/forms/elements/select2/assets/lib/js/select2.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/common/forms/elements/select2/assets/custom/js/select2.init.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/common/forms/elements/multiselect/assets/lib/js/jquery.multi-select.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/common/forms/elements/multiselect/assets/custom/js/multiselect.init.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>
<script src="/mosaicpro/components/modules/admin/notifications/notyfy/assets/lib/js/jquery.notyfy.js?v=v1.0.3-rc2&sv=v0.0.1.1"></script>


<script type="text/javascript">
   function notificar (texto, tipo) {
       notyfy({
        text: texto,
        type: tipo,
        layout: "top",
        timeout: 5000,
    });
   }
</script>

<%- if flash[:notice].present? %>
    <script type="text/javascript">
        notificar("<%= flash[:notice] %>", "information")
    </script>
<% end -%>

<%- if flash[:alert].present? %>
    <script type="text/javascript">
        notificar("<%= flash[:alert] %>", "error")
    </script>
<% end -%>
<%= yield :scripts  %>  
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga_monitora');

  ga_monitora('create', 'UA-80190340-1', 'auto');
  <% if user_signed_in? %>
    ga_monitora('set', 'userId', '<%= current_user.email  %>');
  <% end %>
  ga_monitora('send', 'pageview');

</script>

app/views/layouts/email.html.erb
<div>
  <div style="overflow: hidden;">
    <table width="100%" cellspacing="0" cellpadding="0" style="background:#efefef" align="center" height="auto">
      <tbody>
        <tr>
          <td>
            <table border="0" cellspacing="0" cellpadding="0" width="700" bgcolor="#efefef" align="center" height="68">
              <tbody>
                <tr height="20">
                  <td width="150">&nbsp;</td>
                  <td width="548">&nbsp;</td>
                </tr>
                <tr>
                  <td height="32" valign="bottom" align="center" colspan="2">                    
                    <a href="http://www.to.gov.br" targe="_blank" target="_blank">
                      <img alt="Governo do Tocantins" src="https://barra.to.gov.br/imagens/logo.svg?1527695565" style="VERTICAL-ALIGN:bottom">
                    </a>
                  </td>

                  </tr>
                  <tr height="11">
                    <td width="150">&nbsp;</td>
                    <td width="548">&nbsp;</td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
      <table style="BACKGROUND:#efefef" border="0" cellspacing="0" cellpadding="0" width="100%" align="center">
        <tbody>
          <tr>
            <td>
              <table style="BORDER-BOTTOM:#ddd 1px solid;BORDER-LEFT:#ddd 1px solid;BACKGROUND:#fff;BORDER-TOP:#ddd 1px solid;BORDER-RIGHT:#ddd 1px solid" border="0" cellspacing="0" cellpadding="0" width="700" align="center">
                <tbody>
                  <tr>
                    <td height="20"></td>
                  </tr>
                  <tr>
                    <td>
                      <table border="0" cellspacing="0" cellpadding="0" width="620" align="center">
                        <tbody>
                          <tr>
                            <td height="20"></td>
                          </tr>
                          <tr>
                            <td height="14">&nbsp;</td>
                          </tr>
                          <tr>
                            <td style="LINE-HEIGHT:18px;FONT-FAMILY:arial;COLOR:#666;FONT-SIZE:12px">
                              <p>
                                <%= yield %>
                              </p>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td height="10">&nbsp;</td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
      <table style="BACKGROUND:#efefef" border="0" cellpadding="0" width="100%" align="center" height="auto">
        <tbody>
          <tr>
            <td>
              <table style="BACKGROUND:#efefef" border="0" cellpadding="0" width="100%" align="center" height="auto">
                <tbody>
                  <tr>
                    <td>
                      <table border="0" cellspacing="0" cellpadding="0" width="700" bgcolor="#efefef" align="center" height="165">
                        <tbody>
                        <tr>                          
                              <td style="COLOR:#ccc" height="10" valign="bottom" width="548" align="right">
                                <%= link_to("Portal", "http://www.to.gov.br" , style: "mailer_link_style" ,target: "_blank") %>                            
                                <span style="color:#999999">|</span>
                                <%= link_to("Notícias", "http://secom.to.gov.br/" , style: "mailer_link_style" ,target: "_blank") %>
                                <span style="color:#999999">|</span>
                                <%= link_to("Transparência", "http://transparencia.to.gov.br/" , style: "mailer_link_style" ,target: "_blank") %>
                              </td>
                        </tr>


                          <tr>
                            <td style="LINE-HEIGHT:18px;FONT-FAMILY:arial;COLOR:#999;FONT-SIZE:11px" valign="bottom">

                              <br>
                              <div style="text-align: center" >
                               <br> 
                               <%= link_to("Governo do Estado do Tocantins", "http://www.to.gov.br" , style: "mailer_link_style" ,target: "_blank") %>
                               <br>
                               Palácio Araguaia, Praça dos Girassóis | Palmas - TO 
                               <br/>
                               Fone: 63.3212.4000  | CEP: 77001-900 
                             </div>
                           </td>
                         </tr>
                         <tr>
                          <td height="20">&nbsp;</td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>